-- ⚠️  THIS FILE IS STALE — DO NOT USE AS SCHEMA REFERENCE
-- =============================================================================
-- The cross-repository conceptual schema is:
--   external.reports-hub/docs/schema.sql
--   Relative path from this file: ../../../docs/schema.sql
-- It documents ownership and intended names, but is not an executable or
-- production-authoritative snapshot of constraints, defaults, views, or indexes.
--
-- This file (sql/TB_SEC_REPORTS.sql) was a legacy pg_dump snapshot that had
-- columns (reg_dt, save_time, download_url, article_url) which no longer exist
-- in production. It is kept as a pointer only.
--
-- Production authority: query pg_catalog/information_schema on the live database.
-- =============================================================================
-- Last validated against production: 2026-07-10
-- Production columns (psql \d tbl_sec_reports):
--   report_id, firm_id, board_id, firm_nm, article_title,
--   download_status_yn, writer, telegram_url, mkt_tp,
--   gemini_summary, summary_time, summary_model, archive_path,
--   retry_count, sync_status, pdf_url, pdf_sync_status, pdf_hash,
--   tags, stock_names, sector, fnguide_summary_id,
--   target_price, rating, revision_type, report_type, stock_tickers,
--   report_date, telegram_sent, report_unique_key, save_at,
--   article_text, gdrive_pdf_url
-- =============================================================================
